# Generated by Django 3.2.10 on 2021-12-30 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableno', models.CharField(max_length=255)),
                ('table_status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Preparing'), ('WA', 'Waiting To Deliver'), ('DO', 'Delivered')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=225)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=225)),
                ('meal_image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_meals', to='restaurantOrderingSystem.category')),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField()),
                ('order_status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Preparing'), ('WA', 'Waiting To Deliver'), ('DO', 'Delivered')], default='PE', max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering', to='restaurantOrderingSystem.customer')),
                ('foodlist', models.ManyToManyField(related_name='order', to='restaurantOrderingSystem.Meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='orderlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='order', to='restaurantOrderingSystem.Order'),
        ),
        migrations.CreateModel(
            name='Food_Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_food', to='restaurantOrderingSystem.customer')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='restaurantOrderingSystem.meal')),
            ],
        ),
    ]
