# Generated by Django 3.2.10 on 2021-12-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantOrderingSystem', '0002_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
