# Generated by Django 3.2.10 on 2022-01-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantOrderingSystem', '0004_auto_20220103_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='table_status',
            field=models.CharField(choices=[('PE', 'انتظار التجهيز'), ('PR', 'تجهيز'), ('WA', 'بانتظار التسليم'), ('DO', 'تم التسليم')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PE', 'انتظار التجهيز'), ('PR', 'تجهيز'), ('WA', 'بانتظار التسليم'), ('DO', 'تم التسليم')], default='PE', max_length=2),
        ),
    ]
