# Generated by Django 2.2.4 on 2021-05-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fave_book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
