# Generated by Django 2.2.4 on 2021-05-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0001_initial'),
        ('fave_book', '0002_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fave', models.ManyToManyField(related_name='favebook', to='login_register.users')),
                ('uploadby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login_register.users')),
            ],
        ),
    ]
