# Generated by Django 2.2.4 on 2021-05-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fave_book', '0003_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='uploadby',
            new_name='uploaded_by',
        ),
    ]
